spring.application.name=seid

# --- Configuración MySQL ---
spring.datasource.url=jdbc:mysql://seid-gamr.i.aivencloud.com:20406/seid?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_kys3c64-duW9zh4YMoP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuración JPA / Hibernate ---
# 'update': Crea las tablas si no existen o las actualiza. 
# Úsalo en DEV. En PROD usa 'validate'.
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=true

# Usa el dialecto correcto para MySQL 8 (mejora el rendimiento)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect