spring.application.name=seid

# --- Configuracion MySQL ---
spring.datasource.url=jdbc:mysql://localHost:3306/seid
spring.datasource.username=api_seid
spring.datasource.password=S3p3S3iD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuracion JPA / Hibernate ---
# 'update': Crea las tablas si no existen o las actualiza. 
# Úsalo en DEV. En PROD usa 'validate'.
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (útil para depurar)
spring.jpa.show-sql=false

# El cach� expira 60 segundos despu�s de haber sido escrito
spring.cache.caffeine.spec=expireAfterWrite=60s

spring.output.ansi.enabled=always

# Forzar a que los logs de consola usen UTF-8
logging.charset.console=UTF-8