spring.application.name=seid

# ------------------------
#         SAWGGER
# ------------------------

# Ruta donde SpringDoc buscará tu CSS (relativo a 'static')
springdoc.swagger-ui.custom-css=/css/swagger-custom.css

# Ordenar los endpoints alfabéticamente (por defecto vienen en orden de creación)
springdoc.swagger-ui.operations-sorter=alpha

# Ordenar los grupos (Controladores) alfabéticamente
springdoc.swagger-ui.tags-sorter=alpha

# Desactivar el botón "Try it out" por defecto (para que solo sea lectura)
# springdoc.swagger-ui.supported-submit-methods=get

# Expandir todos los endpoints por defecto (none, list, full)
springdoc.swagger-ui.doc-expansion=none